### ISSUE TITLE
load balancer / backend not idempotent

### ISSUE THREAD

**Issue by albundy83** [outscale/terraform-provider-outscale#496]
Hello,

using latest release 1.0.0 do not work when you instanciate a load balancer.
I use tofu release 
gbellongervais@localhost:~/outscale/osc-rke2.docabilans-sg.old> tofu version
OpenTofu v1.9.0

Using the following code: https://github.com/outscale/osc-k8s-rke-cluster/blob/master/load-balancer.tf and maybe this part: https://github.com/outscale/osc-k8s-rke-cluster/blob/master/load-balancer.tf#L41 

When you start a 2nd time tofu apply, you have the following output:
```yaml
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

OpenTofu will perform the following actions:

  # local_file.lb-kube-workers-ip must be replaced
-/+ resource "local_file" "lb-kube-workers-ip" {
      + content              = "148.x.x.x" # forces replacement
      ~ content_base64sha256 = "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" -> (known after apply)
      ~ content_base64sha512 = "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" -> (known after apply)
      ~ content_md5          = "d41d8cd98f00b204e9800998ecf8427e" -> (known after apply)
      ~ content_sha1         = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
      ~ content_sha256       = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -> (known after apply)
      ~ content_sha512       = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e" -> (known after apply)
      ~ id                   = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[0] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-936d435d",
          - "i-dfcb5ff4",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[1] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-dfcb5ff4",
          - "i-fcf76b61",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[2] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-936d435d",
          - "i-fcf76b61",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms_workers[0] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms_workers" {
      ~ backend_vm_ids     = [
          - "i-89282617",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-workers"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms_workers[1] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms_workers" {
      ~ backend_vm_ids     = [
          - "i-014ca9a2",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-workers"
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 5 to change, 1 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

When you destroy everything and you use 0.12.0 release, no more problem.

**Comment by outscale-toa** [comment]
Hello @albundy83,
Can you try this:
```hcl
resource "outscale_load_balancer_vms" "backend_vms" {
  #count              = var.control_plane_count // remove this line 
  load_balancer_name = outscale_load_balancer.lb-kube-apiserver.load_balancer_name
  #backend_vm_ids     = [outscale_vm.control-planes[count.index].vm_id] // replace this line by
   backend_vm_ids     = [for _, vm in outscale_vm.control-planes : vm.vm_id]
}
```
Best regards,

**Comment by albundy83** [comment]
I have tried to instantiate my infra with the old way.
I encoutered the same error:
```yaml
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

OpenTofu will perform the following actions:

  # local_file.lb-kube-workers-ip must be replaced
-/+ resource "local_file" "lb-kube-workers-ip" {
      + content              = "142.x.x.x" # forces replacement
      ~ content_base64sha256 = "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" -> (known after apply)
      ~ content_base64sha512 = "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" -> (known after apply)
      ~ content_md5          = "d41d8cd98f00b204e9800998ecf8427e" -> (known after apply)
      ~ content_sha1         = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
      ~ content_sha256       = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -> (known after apply)
      ~ content_sha512       = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e" -> (known after apply)
      ~ id                   = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[0] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-62b0b3d6",
          - "i-e17c6eba",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[1] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-c7b00254",
          - "i-e17c6eba",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[2] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms" {
      ~ backend_vm_ids     = [
          - "i-62b0b3d6",
          - "i-c7b00254",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-apiserver"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms_workers[0] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms_workers" {
      ~ backend_vm_ids     = [
          - "i-71d15633",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-workers"
        # (2 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms_workers[1] will be updated in-place
  ~ resource "outscale_load_balancer_vms" "backend_vms_workers" {
      ~ backend_vm_ids     = [
          - "i-44cd6dbb",
            # (1 unchanged element hidden)
        ]
        id                 = "mycluster-test-kube-workers"
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 5 to change, 1 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

And then, I change the loop functions with your loop using for:
```yaml
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy
-/+ destroy and then create replacement

OpenTofu will perform the following actions:

  # local_file.lb-kube-workers-ip must be replaced
-/+ resource "local_file" "lb-kube-workers-ip" {
      + content              = "142.x.x.x" # forces replacement
      ~ content_base64sha256 = "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" -> (known after apply)
      ~ content_base64sha512 = "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" -> (known after apply)
      ~ content_md5          = "d41d8cd98f00b204e9800998ecf8427e" -> (known after apply)
      ~ content_sha1         = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
      ~ content_sha256       = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" -> (known after apply)
      ~ content_sha512       = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e" -> (known after apply)
      ~ id                   = "da39a3ee5e6b4b0d3255bfef95601890afd80709" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[0] has moved to outscale_load_balancer_vms.backend_vms
    resource "outscale_load_balancer_vms" "backend_vms" {
        id                 = "mycluster-test-kube-apiserver"
        # (3 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms[1] will be destroyed
  # (because resource does not use count)
  - resource "outscale_load_balancer_vms" "backend_vms" {
      - backend_ips        = [] -> null
      - backend_vm_ids     = [
          - "i-62b0b3d6",
          - "i-c7b00254",
          - "i-e17c6eba",
        ] -> null
      - id                 = "mycluster-test-kube-apiserver" -> null
      - load_balancer_name = "mycluster-test-kube-apiserver" -> null
    }

  # outscale_load_balancer_vms.backend_vms[2] will be destroyed
  # (because resource does not use count)
  - resource "outscale_load_balancer_vms" "backend_vms" {
      - backend_ips        = [] -> null
      - backend_vm_ids     = [
          - "i-62b0b3d6",
          - "i-c7b00254",
          - "i-e17c6eba",
        ] -> null
      - id                 = "mycluster-test-kube-apiserver" -> null
      - load_balancer_name = "mycluster-test-kube-apiserver" -> null
    }

  # outscale_load_balancer_vms.backend_vms_workers[0] has moved to outscale_load_balancer_vms.backend_vms_workers
    resource "outscale_load_balancer_vms" "backend_vms_workers" {
        id                 = "mycluster-test-kube-workers"
        # (3 unchanged attributes hidden)
    }

  # outscale_load_balancer_vms.backend_vms_workers[1] will be destroyed
  # (because resource does not use count)
  - resource "outscale_load_balancer_vms" "backend_vms_workers" {
      - backend_ips        = [] -> null
      - backend_vm_ids     = [
          - "i-44cd6dbb",
          - "i-71d15633",
        ] -> null
      - id                 = "mycluster-test-kube-workers" -> null
      - load_balancer_name = "mycluster-test-kube-workers" -> null
    }

Plan: 1 to add, 0 to change, 4 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

local_file.lb-kube-workers-ip: Destroying... [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
local_file.lb-kube-workers-ip: Destruction complete after 0s
outscale_load_balancer_vms.backend_vms[1]: Destroying... [id=mycluster-test-kube-apiserver]
outscale_load_balancer_vms.backend_vms_workers[1]: Destroying... [id=mycluster-test-kube-workers]
outscale_load_balancer_vms.backend_vms[2]: Destroying... [id=mycluster-test-kube-apiserver]
local_file.lb-kube-workers-ip: Creating...
local_file.lb-kube-workers-ip: Creation complete after 0s [id=4966f77f2b9038780ebeaaf65a1c9299ebf53e11]
outscale_load_balancer_vms.backend_vms_workers[1]: Destruction complete after 0s
outscale_load_balancer_vms.backend_vms[1]: Destruction complete after 0s
╷
│ Error: failure unlinking backend_ips from LBU: 400 Bad Request
```
As you can see, it encountered the error "│ Error: failure unlinking backend_ips from LBU: 400 Bad Request"

What do you think ?
